name: "Trivy Container Scan"
description: "Scan container images with Trivy, post PR comments, upload SARIF"

inputs:
  image_ref:
    description: "Image to scan (e.g., 'myapp:latest')"
    required: true
  image_name:
    description: "Display name for comments (defaults to image_ref)"
    required: false
    default: ""
  scanners:
    description: "Trivy scanners to run"
    required: false
    default: "vuln,secret"
  severity:
    description: "Severity levels to report"
    required: false
    default: "CRITICAL,HIGH,MEDIUM,LOW"
  exit_code:
    description: "Exit code when issues found (0 to not fail)"
    required: false
    default: "0"
  github_token:
    description: "GitHub token for PR comments"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Cache Trivy
      uses: actions/cache@v4
      with:
        path: ~/.cache/trivy
        key: trivy-${{ runner.os }}
        restore-keys: trivy-

    - name: Generate safe file suffix
      id: suffix
      shell: bash
      run: |
        SUFFIX=$(echo "${{ inputs.image_ref || inputs.image_name }}" | tr '/:@' '-')
        echo "value=${SUFFIX}" >> "$GITHUB_OUTPUT"

    - name: Trivy scan (JSON)
      uses: aquasecurity/trivy-action@0.33.1
      with:
        image-ref: ${{ inputs.image_ref }}
        scanners: ${{ inputs.scanners }}
        exit-code: 0
        severity: ${{ inputs.severity }}
        format: json
        output: trivy-results-${{ steps.suffix.outputs.value }}.json

    - name: Convert to table
      shell: bash
      run: |
        trivy convert --format table --output trivy-results-${{ steps.suffix.outputs.value }}.txt trivy-results-${{ steps.suffix.outputs.value }}.json

    - name: Convert to SARIF
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      shell: bash
      run: |
        trivy convert --format sarif --output trivy-results-${{ steps.suffix.outputs.value }}.sarif trivy-results-${{ steps.suffix.outputs.value }}.json

    - name: Upload SARIF to GitHub Security
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: trivy-results-${{ steps.suffix.outputs.value }}.sarif
        category: container-security-${{ inputs.image_name || inputs.image_ref }}

    - name: Log results
      shell: bash
      run: |
        DISPLAY_NAME="${{ inputs.image_name || inputs.image_ref }}"
        RESULTS_FILE="trivy-results-${{ steps.suffix.outputs.value }}.txt"
        echo "::group::Trivy Scan Results (${DISPLAY_NAME})"
        if [ -s "$RESULTS_FILE" ]; then
          cat "$RESULTS_FILE"
        else
          echo "No issues found!"
        fi
        echo "::endgroup::"

    - name: Prepare PR comment
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        MAX_CHARS=60000
        RESULTS_FILE="trivy-results-${{ steps.suffix.outputs.value }}.txt"
        COMMENT_FILE="trivy-comment-${{ steps.suffix.outputs.value }}.md"
        FILE_SIZE=$(wc -c < "$RESULTS_FILE" || echo "0")
        DISPLAY_NAME="${{ inputs.image_name || inputs.image_ref }}"

        {
          echo "## Container Security Scan (${DISPLAY_NAME})"
          echo ""
          if [ ! -s "$RESULTS_FILE" ]; then
            echo "**No vulnerabilities found!**"
          else
            echo "<details>"
            echo "<summary>Click to expand results</summary>"
            echo ""
            echo '```'
            if [ "$FILE_SIZE" -gt "$MAX_CHARS" ]; then
              head -c "$MAX_CHARS" "$RESULTS_FILE"
              echo ""
              echo "... (output truncated - exceeded ${MAX_CHARS} characters)"
              echo "See full results in workflow logs"
            else
              cat "$RESULTS_FILE"
            fi
            echo '```'
            echo ""
            echo "</details>"
          fi
        } > "$COMMENT_FILE"

    - name: Post PR comment
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: trivy-scan-${{ inputs.image_name || inputs.image_ref }}
        path: trivy-comment-${{ steps.suffix.outputs.value }}.md
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Check for failures
      if: inputs.exit_code != '0'
      shell: bash
      run: |
        trivy convert --format table --exit-code ${{ inputs.exit_code }} --severity ${{ inputs.severity }} trivy-results-${{ steps.suffix.outputs.value }}.json
