name: zap-nightly
on:
  schedule: [{ cron: "0 1 * * *" }]
  workflow_dispatch:
jobs:
  load-targets:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.mk.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: mk
        run: |
          output=$(python3 - <<'EOF'
          import yaml, json, sys
          with open(".github/security/targets.yml") as f:
              data = yaml.safe_load(f)
          print(f"matrix={json.dumps({'include': data['services']})}")
          EOF
          )
          echo "$output" >> $GITHUB_OUTPUT
  zap-fanout:
    needs: load-targets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.load-targets.outputs.matrix) }}
    steps:
      - name: Call reusable ZAP
        uses: ./.github/workflows/reuse-zap.yml
        with:
          service_name: ${{ matrix.name }}
          target_url: ${{ matrix.url }}
          auth_type: ${{ matrix.auth.type || 'none' }}
          secret_name: ${{ matrix.auth.secret_name || '' }}
